### ISSUE TITLE
带API运行报错，提示如下

### ISSUE THREAD

**Issue by wyr0125** [LiangYang666/ChatAnywhere#2]
`OPANAI_API_KEY=sk-KjLVTU2SzCKEXXXXXXXXXXBlbkFJDi8Me4o2KcrQMKd1fc2j : 无法将“OPANAI_API_KEY=sk-KjLVTU2SzCKEXXXXXXXXXXBl
bkFJDi8Me4o2KcrQMKd1fc2j”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径
正确，然后再试一次。
所在位置 行:1 字符: 1
+ OPANAI_API_KEY=sk-KjLVTU2SzCKEXXXXXXXXXBlbkFJDi8Me4o2KcrQMKd1fc2j py ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (OPANAI_API_KEY=...4o2KcrQMKd1fc2j:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException`

**Comment by wyr0125** [comment]
```
PS E:\Projects\ChatAnywhere> python .\main.py
Traceback (most recent call last):
  File "E:\Projects\ChatAnywhere\main.py", line 147, in <module>
    app = ChatAnywhereApp(root)
  File "E:\Projects\ChatAnywhere\main.py", line 42, in __init__
    self.ent_apikey.insert(0, API_KEY)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 3095, in insert
    self.tk.call(self._w, 'insert', index, string)
_tkinter.TclError: wrong # args: should be ".!entry insert index text"
```
直接运行报这个错误

**Comment by LiangYang666** [comment]
请问你是怎么设置apikey的，设置环境变量？还是在代码中直接改？

**Comment by couurh** [comment]
> 请问你是怎么设置apikey的，设置环境变量？还是在代码中直接改？

同样的问题，在代码中直接改的。
